# Generated by Django 2.2.6 on 2020-04-24 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200414_0537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('recipe_id', models.CharField(max_length=256)),
                ('recipe_name', models.CharField(max_length=256)),
                ('marketing_description', models.CharField(max_length=256)),
                ('allergen_attributes', models.CharField(max_length=256)),
                ('dietary_attributes', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'serviceRecipeNutrition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=256)),
                ('recipe_description', models.CharField(blank=True, default='', max_length=256)),
                ('preparation_time', models.CharField(blank=True, default='', max_length=256)),
                ('number_of_servings', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calories_per_serving', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='allergic_food',
            field=djongo.models.fields.ListField(blank=True, default=list, null=True),
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_entry', models.DateTimeField(max_length=100, null=True)),
                ('meal_type', models.CharField(choices=[(1, 'Breakfast'), (2, 'Lunch'), (3, 'Dinner'), (4, 'Snack')], max_length=100)),
                ('is_custom_recipe', models.BooleanField(default=False)),
                ('custom_recipe', models.ManyToManyField(blank=True, null=True, to='users.CustomRecipe')),
                ('meals', models.ManyToManyField(to='users.Meals')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
