# Generated by Django 2.2.6 on 2020-04-30 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200429_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrecipe',
            name='calories_per_serving',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='customrecipe',
            name='number_of_servings',
            field=models.FloatField(),
        ),
    ]
