# Generated by Django 2.2.6 on 2020-04-30 00:05

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200430_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dietary_preferences',
            field=djongo.models.fields.ListField(default=list),
        ),
    ]
