# Generated by Django 2.2.6 on 2020-04-30 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200430_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='dietary_preferences',
            new_name='meal_type',
        ),
    ]
