# Generated by Django 2.2.6 on 2020-05-01 23:21

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200430_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='meal_type',
            field=djongo.models.fields.ListField(blank=True, default=list, null=True),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('profile_id', 'recipe_id'), name='name of constraint'),
        ),
    ]
