# Generated by Django 2.2.6 on 2020-05-02 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200501_2321'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating',
            name='name of constraint',
        ),
    ]
