# Generated by Django 2.2.6 on 2020-05-02 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200502_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='recipe_id',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='users.Meals'),
        ),
    ]
