# Generated by Django 2.2.6 on 2020-05-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200502_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='meal_type',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='activity',
            field=models.IntegerField(blank=True, choices=[(1, 'Sedentary'), (2, 'Moderate'), (3, 'Active'), (4, 'Fiber')], null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(blank=True, choices=[(1, '1-3'), (2, '4-8'), (3, '9-13'), (4, '14-18'), (5, '19-30'), (6, '31-50'), (7, '51-99')], null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='meal_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Vegan'), (2, 'Vegetarian'), (3, 'Halal'), (4, 'Meat'), (5, 'Kosher')], null=True),
        ),
    ]
