# Generated by Django 2.2.6 on 2020-05-14 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200514_0223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='meal_type',
            new_name='meal_period',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='activity',
            new_name='activity_level',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='meal_type',
            new_name='meal_period',
        ),
    ]
