# Generated by Django 2.2.6 on 2020-05-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200514_0225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='meal_period',
            new_name='dietary_preference',
        ),
        migrations.RenameField(
            model_name='diary',
            old_name='meal_type',
            new_name='meal_period',
        ),
    ]
