# Generated by Django 2.2.6 on 2020-05-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200514_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='activity_level',
        ),
        migrations.AddField(
            model_name='customuser',
            name='activity',
            field=models.IntegerField(blank=True, choices=[(1, 'Sedentary'), (2, 'Moderate'), (3, 'Active')], null=True),
        ),
    ]
