# Generated by Django 2.2.6 on 2020-05-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200514_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRecipeNutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'serviceRecipeNutrition',
                'managed': False,
            },
        ),
    ]
