# Generated by Django 2.2.6 on 2020-05-28 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_servicerecipenutrition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceRecipeNutrition',
        ),
    ]
