# Generated by Django 2.2.6 on 2020-05-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_delete_servicerecipenutrition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMenuitemsFlat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=256, null=True)),
                ('location', models.CharField(blank=True, max_length=256, null=True)),
                ('service_menu_id', models.IntegerField(blank=True, null=True)),
                ('service_date', models.CharField(blank=True, max_length=256, null=True)),
                ('meal_period_id', models.IntegerField(blank=True, null=True)),
                ('meal_period', models.CharField(blank=True, max_length=256, null=True)),
                ('service_area_id', models.IntegerField(blank=True, null=True)),
                ('service_area_name', models.CharField(blank=True, max_length=256, null=True)),
                ('sub_location_id', models.IntegerField(blank=True, null=True)),
                ('sub_location_order', models.IntegerField(blank=True, null=True)),
                ('sub_location_name', models.CharField(blank=True, max_length=256, null=True)),
                ('sub_location', models.CharField(blank=True, max_length=256, null=True)),
                ('menu_item_order', models.CharField(blank=True, max_length=256, null=True)),
                ('service_menu_item_id', models.IntegerField(blank=True, null=True)),
                ('master_system_id', models.IntegerField(blank=True, null=True)),
                ('recipe_id', models.CharField(blank=True, max_length=256, null=True)),
                ('recipe_name', models.CharField(blank=True, max_length=256, null=True)),
                ('recipe_marketing_name', models.CharField(blank=True, max_length=256, null=True)),
                ('recipe_short_name', models.CharField(blank=True, max_length=256, null=True)),
                ('production_area_id', models.IntegerField(blank=True, null=True)),
                ('production_area_name', models.CharField(blank=True, max_length=256, null=True)),
                ('is_mto', models.CharField(blank=True, max_length=256, null=True)),
                ('serving_size_uom_id', models.IntegerField(blank=True, null=True)),
                ('number_of_servings', models.CharField(blank=True, max_length=256, null=True)),
                ('serving_size_number', models.CharField(blank=True, max_length=256, null=True)),
                ('serving_size_description', models.CharField(blank=True, max_length=256, null=True)),
                ('serving_size_fraction_id', models.IntegerField(blank=True, null=True)),
                ('service_size_fraction_description', models.CharField(blank=True, max_length=256, null=True)),
                ('serving_size_display', models.CharField(blank=True, max_length=256, null=True)),
                ('is_temp_required', models.CharField(blank=True, max_length=256, null=True)),
                ('food_cost', models.FloatField(blank=True, null=True)),
                ('acceptability_factor', models.FloatField(blank=True, null=True)),
                ('planned_count', models.FloatField(blank=True, null=True)),
                ('prep_count', models.FloatField(blank=True, null=True)),
                ('sold_count', models.FloatField(blank=True, null=True)),
                ('on_hand_count', models.FloatField(blank=True, null=True)),
                ('leftover_count', models.FloatField(blank=True, null=True)),
                ('waste_count', models.FloatField(blank=True, null=True)),
                ('smi_row_no', models.IntegerField(blank=True, null=True)),
                ('is_result_required', models.CharField(blank=True, max_length=256, null=True)),
                ('comments', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'serviceMenuitemsFlat',
                'managed': False,
            },
        ),
    ]
