# Generated by Django 2.2.6 on 2020-06-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_servicemenuitemsflat'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.CharField(blank=True, max_length=256, null=True)),
                ('recipe_name', models.CharField(blank=True, max_length=256, null=True)),
                ('primary_attributes', models.CharField(max_length=256)),
                ('ingredients', models.CharField(max_length=256)),
                ('recipe_HEI_score', models.FloatField(blank=True, null=True)),
                ('norm_HEI_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'new_recipes',
                'managed': False,
            },
        ),
    ]
