# Generated by Django 2.2.6 on 2020-06-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_newrecipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='testFun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
