# Generated by Django 2.2.6 on 2020-06-22 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_testfun'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testfun',
            options={'managed': False},
        ),
    ]
