# Generated by Django 2.2.6 on 2020-06-23 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20200622_2349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testFun',
        ),
    ]
